FROM wnameless/oracle-xe-11g

### oracledb
# docker run -d -p 49166:8080 -p 49161:1521 --name oracledb  -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g

# http://0.0.0.0:49166/apex/
# internal, admin, oracle


# https://hub.docker.com/r/wnameless/oracle-xe-11g/
# hostname: localhost
# port: 49161
# sid: xe
# username: system
# password: oracle
# Password for SYS & SYSTEM